Repository MatterMiners/tardis, pull requests merged in 2021-03, with the labels that each got.

#173 Fix htcondor site adapter
  docs/source/changelog.rst
  docs/source/changes/173.fix_meta_data_translation_htcondor.yaml
  tardis/adapters/sites/htcondor.py
  tardis/adapters/sites/slurm.py
  tardis/interfaces/siteadapter.py
  tardis/resources/drone.py
  tardis/utilities/utils.py
  tests/adapters_t/sites_t/test_htcondorsiteadapter.py
  tests/adapters_t/sites_t/test_slurm.py
  tests/interfaces_t/test_siteadapter.py
Labels: bug

#175 Fixing rare `ValueError`s in `get_resource_ratios`
  docs/source/changelog.rst
  docs/source/changes/175.fix_resource_ratios.yaml
  tardis/adapters/batchsystems/htcondor.py
  tests/adapters_t/batchsystems_t/test_htcondor.py
Labels: bug

#178 Switch CI to GitHub actions
  .github/workflows/unittests.yml
  .github/workflows/verification.yml
  .travis.yml
  README.md
  setup.py
Labels: Improvement

#180 Fix PyPy compatibility
  .github/workflows/unittests.yml
  CONTRIBUTORS
  tardis/plugins/sqliteregistry.py
Labels: Improvement, enhancement
