Repository MatterMiners/tardis, pull requests merged in 2023-08, with the labels that each got.

#308 Deprecated lancium support
  docs/source/adapters/site.rst
  docs/source/api/tardis.adapters.sites.lancium.rst
  docs/source/api/tardis.adapters.sites.rst
  docs/source/changelog.rst
  setup.py
  tardis/adapters/sites/lancium.py
  tests/adapters_t/sites_t/test_lancium.py
Labels: Cleanup

#306 Add error handling when updating non-existing record
  tardis/plugins/auditor.py
  tests/plugins_t/test_auditor.py
Labels: bug, Improvement

#309 Fix broken yaml tags in the documentation
  CONTRIBUTORS
  docs/source/changelog.rst
  docs/source/index.rst
Labels: Improvement, Cleanup

#304 Deprecate eol python versions 3.6 and 3.7, enable support for 3.11
  .github/workflows/deployment-tests.yml
  .github/workflows/unittests.yml
  .pre-commit-config.yaml
  containers/cobald-tardis-deployment-test-env/Dockerfile.centos7
  containers/cobald-tardis-deployment-test-env/Dockerfile.centosstream8
  containers/cobald-tardis-deployment-test-env/Dockerfile.rockylinux8
  containers/cobald-tardis-htcondor/Dockerfile
  containers/cobald-tardis/Dockerfile
  docs/source/changelog.rst
  docs/source/changes/304.deprecate_python_36_37.yaml
  setup.py
  tardis/resources/drone.py
  tardis/utilities/asyncbulkcall.py
  tests/adapters_t/sites_t/test_fakesite.py
  tests/adapters_t/sites_t/test_htcondorsiteadapter.py
  tests/adapters_t/sites_t/test_slurm.py
  tests/agents_t/test_batchsystemagent.py
  tests/agents_t/test_siteagent.py
  tests/interfaces_t/test_batchsystemadapter.py
  tests/interfaces_t/test_siteadapter.py
  tests/plugins_t/test_auditor.py
  tests/plugins_t/test_elasticsearchmonitoring.py
  tests/plugins_t/test_prometheusmonitoring.py
  tests/plugins_t/test_sqliteregistry.py
  tests/plugins_t/test_telegrafmonitoring.py
  tests/resources_t/test_drone.py
  tests/resources_t/test_dronestates.py
  tests/rest_t/test_service.py
  tests/utilities_t/test_asyncbulkcall.py
  tests/utilities_t/test_asynccachemap.py
  tests/utilities_t/test_pipeline.py
Labels: enhancement

#310 Change readthedocs python version
  .readthedocs.yml
  docs/source/changelog.rst
  setup.py
Labels: bug
